
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jan 28 08:43:57 COT 2015
//----------------------------------------------------

package ejerciociocupvero;

import java.io.*;
import java_cup.runtime.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Wed Jan 28 08:43:57 COT 2015
  */
public class AnalizadorSintac extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public AnalizadorSintac() {super();}

  /** Constructor which sets the default scanner. */
  public AnalizadorSintac(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public AnalizadorSintac(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\007\000\002\002\004\000\002\002\004\000\002\003" +
    "\011\000\002\004\004\000\002\004\004\000\002\004\004" +
    "\000\002\004\004" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\021\000\004\010\004\001\002\000\004\012\011\001" +
    "\002\000\004\002\010\001\002\000\004\013\007\001\002" +
    "\000\004\002\001\001\002\000\004\002\000\001\002\000" +
    "\004\014\012\001\002\000\004\014\014\001\002\000\004" +
    "\011\021\001\002\000\012\004\015\005\020\006\017\007" +
    "\016\001\002\000\006\011\ufffe\013\ufffe\001\002\000\006" +
    "\011\ufffb\013\ufffb\001\002\000\006\011\ufffc\013\ufffc\001" +
    "\002\000\006\011\ufffd\013\ufffd\001\002\000\004\014\022" +
    "\001\002\000\004\014\014\001\002\000\004\013\uffff\001" +
    "\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\021\000\006\002\004\003\005\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\004\012\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\004\022\001\001\000\002\001\001" +
    "" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$AnalizadorSintac$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$AnalizadorSintac$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$AnalizadorSintac$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



	public void report_error(String message, Object info) {
       	StringBuffer m = new StringBuffer("Error");
		System.out.println("Mensaje: "+message);
		System.out.println("info: "+info.toString());
		if(info instanceof java_cup.runtime.Symbol) {
			java_cup.runtime.Symbol s=((java_cup.runtime.Symbol)info);
			/* Comprueba si el numero de línea es mayor o igual que cero */
			if(s.left >= 0) {
				m.append(" en linea "+(s.left+1));
				/*Comprueba si el numero de columna es mayoro igual que cero */
				if (s.right >= 0)
					m.append(", y columna "+(s.right+1));
			}
		}
		m.append(" : "+message);
		System.err.println(m);
    }
public void report_fatal_error(String message, Object info) {
       	report_error(message, info);
		System.exit(1);
    }

        public static void main(String[] args){
        try {
            AnalizadorSintactico asin = new AnalizadorSintactico(
                    new AnalizadorLexico( new FileReader(args[0])));
            Object result = asin.parse().value;
            System.out.println("\n*** Resultados finales ***");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$AnalizadorSintac$actions {
  private final AnalizadorSintac parser;

  /** Constructor */
  CUP$AnalizadorSintac$actions(AnalizadorSintac parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$AnalizadorSintac$do_action(
    int                        CUP$AnalizadorSintac$act_num,
    java_cup.runtime.lr_parser CUP$AnalizadorSintac$parser,
    java.util.Stack            CUP$AnalizadorSintac$stack,
    int                        CUP$AnalizadorSintac$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$AnalizadorSintac$result;

      /* select the action based on the action number */
      switch (CUP$AnalizadorSintac$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // unidad ::= NUMERO HORA 
            {
              Object RESULT =null;
		int hleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.peek()).left;
		int hright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.peek()).right;
		Object h = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintac$stack.peek()).value;
		
              RESULT = h.toString();
            
              CUP$AnalizadorSintac$result = parser.getSymbolFactory().newSymbol("unidad",2, ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.elementAt(CUP$AnalizadorSintac$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // unidad ::= NUMERO SEGUNDOS 
            {
              Object RESULT =null;
		int sgleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.peek()).left;
		int sgright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.peek()).right;
		Object sg = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintac$stack.peek()).value;
		
              RESULT = sg.toString();
            
              CUP$AnalizadorSintac$result = parser.getSymbolFactory().newSymbol("unidad",2, ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.elementAt(CUP$AnalizadorSintac$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // unidad ::= NUMERO METROS 
            {
              Object RESULT =null;
		int mleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.peek()).left;
		int mright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.peek()).right;
		Object m = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintac$stack.peek()).value;
		
              RESULT = m.toString();
            
              CUP$AnalizadorSintac$result = parser.getSymbolFactory().newSymbol("unidad",2, ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.elementAt(CUP$AnalizadorSintac$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // unidad ::= NUMERO KILOMETROS 
            {
              Object RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.elementAt(CUP$AnalizadorSintac$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.elementAt(CUP$AnalizadorSintac$top-1)).right;
		Integer n = (Integer)((java_cup.runtime.Symbol) CUP$AnalizadorSintac$stack.elementAt(CUP$AnalizadorSintac$top-1)).value;
		int kleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.peek()).left;
		int kright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.peek()).right;
		Object k = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintac$stack.peek()).value;
		
              RESULT = k.toString();
            
              CUP$AnalizadorSintac$result = parser.getSymbolFactory().newSymbol("unidad",2, ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.elementAt(CUP$AnalizadorSintac$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // expresion ::= ID IGUAL NUMERO unidad DIV NUMERO unidad 
            {
              Object RESULT =null;

              CUP$AnalizadorSintac$result = parser.getSymbolFactory().newSymbol("expresion",1, ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.elementAt(CUP$AnalizadorSintac$top-6)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= lista EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.elementAt(CUP$AnalizadorSintac$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.elementAt(CUP$AnalizadorSintac$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintac$stack.elementAt(CUP$AnalizadorSintac$top-1)).value;
		RESULT = start_val;
              CUP$AnalizadorSintac$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.elementAt(CUP$AnalizadorSintac$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$AnalizadorSintac$parser.done_parsing();
          return CUP$AnalizadorSintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // lista ::= expresion PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$AnalizadorSintac$result = parser.getSymbolFactory().newSymbol("lista",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.elementAt(CUP$AnalizadorSintac$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintac$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

