
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 10 03:46:38 COT 2015
//----------------------------------------------------

package ejerciociocup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMA = 6;
  public static final int ID = 5;
  public static final int error = 1;
  public static final int LLAVE_DERECHA = 3;
  public static final int EOF = 0;
  public static final int DOS_PUNTOS = 4;
  public static final int LLAVE_IZQUIERDA = 2;
}

